version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: stackrhub
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/stackrhub
      SPRING_DATASOURCE_USERNAME: db_user
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - db
    ports:
      - "8080:8080"

  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres_data:
